# Production docker-compose configuration for Chatter
# Uses external PostgreSQL database (not the bundled postgres container)
# Usage: docker-compose -f docker-compose.prod.yml up -d

services:
  # Chatter Application
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: chatter:latest
    container_name: chatter-app
    restart: unless-stopped
    ports:
      - "8006:8006"
    environment:
      # Application settings
      - ENVIRONMENT=production
      - PORT=8006

      # Database connection (using external PostgreSQL)
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}

      # JWT Secret (must be set in .env file)
      - SECRET_KEY=${SECRET_KEY}

      # CORS settings
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://kevsrobots.com}

    volumes:
      # Mount data directory
      - ./data:/app/data

      # Mount logs directory
      - ./logs:/app/logs

    # No depends_on since we're using external database
    networks:
      - chatter-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8006}/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

networks:
  chatter-network:
    driver: bridge
