# Production docker-compose configuration for Chatter
# Uses external PostgreSQL database (not the bundled postgres container)
# Usage: docker-compose -f docker-compose.prod.yml up -d

services:
  # Chatter Application
  app:
    env_file:
      - ./app/.env  # Load credentials from app/.env
    build:
      context: .
      dockerfile: Dockerfile
      pull: true
      args:
        - CACHEBUST=${CACHEBUST:-1}
    image: chatter:latest
    container_name: chatter-app
    restart: unless-stopped
    ports:
      - "8006:8006"
    environment:
      # Application settings
      - ENVIRONMENT=production
      - PORT=8006

      # DATABASE_URL, SECRET_KEY, and ALLOWED_ORIGINS are loaded from app/.env in the container
      # Do not override them here to avoid issues with URL-encoded passwords

    volumes:
      # Mount data directory
      - ./data:/app/data

      # Mount logs directory
      - ./logs:/app/logs

    # No depends_on since we're using external database
    networks:
      - chatter-network

    # Override entrypoint to skip database wait check (connection is verified to work)
    entrypoint: ""
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8006"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

networks:
  chatter-network:
    driver: bridge
