-- Migration: Add password reset code fields for one-time password reset
-- Date: 2025-10-23
-- Description: Allows admins to generate reset codes for users who forgot passwords

-- =====================================================
-- Add password reset code fields to user table
-- =====================================================

ALTER TABLE "user" ADD COLUMN IF NOT EXISTS password_reset_code VARCHAR;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS code_expires_at TIMESTAMP;

-- Add index for efficient code lookups
CREATE INDEX IF NOT EXISTS idx_user_password_reset_code ON "user"(password_reset_code) WHERE password_reset_code IS NOT NULL;

-- Add comments for documentation
COMMENT ON COLUMN "user".password_reset_code IS 'One-time code for password reset (generated by admin)';
COMMENT ON COLUMN "user".code_expires_at IS 'Expiration timestamp for reset code (24 hours from generation)';
